---
title: "Signal to Noise Analysis"
author: "Nate Olson"
date: "3/6/2018"
output: html_document
---

```{r message = FALSE, warning = FALSE}
library(ProjectTemplate)
load.project()
library(trelliscopejs)
```

```{r}
sig_noise_df <- bind_rows(
        sig_noise_bray_df,
        sig_noise_jaccard_df,
        sig_noise_unifrac_df,
        sig_noise_wunifrac_df)
```

```{r}
sig_noise_df <- sig_noise_df %>% 
    rowwise() %>% 
    mutate(mean_noise = mean(c(mean_rep_dist, mean_pre_dist),na.rm = TRUE), 
           median_noise = mean(c(mean_rep_dist, mean_pre_dist), na.rm = TRUE),
            mean_sig_noise = mean_dist/mean_noise,
           median_sig_noise = median_dist/median_noise)
```

```{r message = FALSE, warning = FALSE}
sig_noise_df %>%
    mutate(seq_lab_run = paste0(seq_lab, seq_run)) %>% 
    group_by(pipe, dist_method) %>% 
    nest() %>% 
    mutate(panel = map_plot(data, ~{
        ggplot(.) + 
            geom_path(aes(x = t_fctr, y = median_sig_noise, color = method)) +
            facet_grid(biosample_id~seq_lab_run) + theme_bw() + 
            labs(x = "Titration", y = "Signal/Noise", color = "Normalization")}
   )) %>%
  trelliscope(name = "signal to noise", nrow = 1, ncol = 1, self_contained = TRUE)
```

```{r message = FALSE, warning = FALSE}
sig_noise_df %>% filter(method == "RAW") %>% 
    mutate(seq_lab_run = paste0(seq_lab, seq_run)) %>% 
    ggplot() + 
    ggridges::geom_density_ridges(aes(x = median_noise, y = pipe, fill = seq_lab_run), alpha = 0.25) + 
    facet_grid(dist_method~biosample_id, scales = "free_y") + 
    theme_bw()
```

```{r message = FALSE, warning = FALSE}
sig_noise_df %>% filter(method == "RAW") %>% 
    mutate(seq_lab_run = paste0(seq_lab, seq_run)) %>% 
    ggplot() + 
    ggridges::geom_density_ridges(aes(x = median_sig_noise, y = pipe, fill = seq_lab_run), alpha = 0.25) + 
    facet_grid(biosample_id~dist_method, scales = "free_y") + 
    theme_bw()
```

```{r}
sig_noise_df %>% filter(method == "RAW", t_fctr == 0) %>% 
    mutate(seq_lab_run = paste0(seq_lab, seq_run)) %>% 
    ggplot() + 
    geom_boxplot(aes(x = pipe, y = median_sig_noise, fill = seq_lab_run)) + 
    facet_grid(dist_method~., scales = "free_y") + 
    theme_bw()
```

```{r}
sig_noise_df %>% filter(method == "RAW", t_fctr != 0) %>% 
    mutate(seq_lab_run = paste0(seq_lab, seq_run)) %>% 
    ggplot() + 
    geom_boxplot(aes(x = pipe, y = median_sig_noise, fill = seq_lab_run)) + 
    facet_grid(dist_method~t_fctr, scales = "free_y") + 
    theme_bw()
```

```{r}
sig_noise_df %>% filter(method == "RAW", t_fctr != 0) %>% 
    mutate(seq_lab_run = paste0(seq_lab, seq_run)) %>% 
    mutate(pipe = if_else(pipe == "deblur", "qiimeDeblur",pipe)) %>% 
    filter(seq_lab_run == "jhu2") %>% 
    ggplot() + 
    geom_point(aes(x = pipe, y = median_sig_noise, color = biosample_id)) + 
    facet_grid(dist_method~t_fctr, scales = "free_y") + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = -45, hjust = 0))
```

