---
title: "signal to noise analysis summary"
author: "Nate Olson"
date: '`r Sys.Date()`'
output:
  bookdown::html_document2: 
    toc: FALSE
---
```{r}
library(ProjectTemplate)
load.project()
library(ggfortify)
library(ggpubr)
library(ggthemes)
library(stringr)
source("src/plot_color_definitions.R")
## Consider using https://github.com/bbolker/broom.mixed/tree/master/R for tidying lme
```

## Data munging
```{r}
sig_noise_df <- bind_rows(
        sig_noise_bray_df,
        sig_noise_jaccard_df,
        sig_noise_unifrac_df,
        sig_noise_wunifrac_df)
```

```{r}
sig_noise_df <- sig_noise_df %>% 
    rowwise() %>% 
    mutate(mean_noise = mean(c(mean_rep_dist, mean_pre_dist),na.rm = TRUE), 
           median_noise = mean(c(mean_rep_dist, mean_pre_dist), na.rm = TRUE),
            mean_sig_noise = mean_dist/mean_noise,
           median_sig_noise = median_dist/median_noise)
```

```{r}
auc_summary <- sig_noise_df %>% 
    filter(method == "RAW") %>% 
    mutate(t_eval = 2^-t_fctr) %>% 
    group_by(pipe, method, dist_method, seq_lab, seq_run, biosample_id) %>% 
    summarise(n_t = n(), 
              auc = -pracma::trapz(x = t_eval, y = median_sig_noise)) %>% 
    mutate(metric = str_remove(dist_method, "_dist")) %>% 
    mutate(f_type = if_else(metric %in% c("unifrac","wunifrac"), 
                        "Phylogenetic","Taxonomic"),
       weight = if_else(metric %in% c("unifrac","jaccard"),
                        "Unweighted", "Weighted")) 
```



## Signal to noise figure 

```{r}
auc_summary %>% 
    ungroup() %>% 
    mutate(seq_lab_run = paste(seq_lab, seq_run)) %>% 
        mutate(pipe = if_else(pipe == "deblur", "qiimeDeblur",pipe),
           pipe = factor(pipe)) %>% 
    
    mutate(x_offset = if_else(seq_lab == "jhu", -0.3  + 0.1 * seq_run, 0.1 * seq_run),
           x_pos = as.numeric(pipe) + x_offset) %>% 
    ggplot() + 
    geom_blank(aes(x = pipe)) + 
    geom_line(aes(x = x_pos, y = auc,group = paste(pipe,seq_lab_run)), color = "grey60") + 
    geom_point(aes(x = x_pos, y = auc, color = seq_lab_run, shape = biosample_id)) + 
    facet_grid(weight~f_type) +
    # facet_grid(dist_method~., scales = "free_y") + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = -45, hjust = 0)) + 
    labs(x = "Pipeline", y = "Weighted Average Signal/Noise", 
         color = "Seq Run", shape = "Individual") + 
    scale_y_continuous(trans = "log2")
```


## Signal to noise stats 
```{r}
auc_fit <- auc_summary %>% 
    ungroup() %>% 
    mutate(seq_run = as.numeric(seq_run),
           seq_run_num = if_else(seq_lab == "jhu", seq_run, 2 + seq_run),
           seq_run_num = factor(seq_run_num)) %>% 
    group_by(dist_method) %>%
    nest() %>%
    mutate(fit = map(data, ~lm(log10(auc) ~ pipe + seq_run_num + biosample_id, data = .)))
```



## Norm effect
```{r}
library(lme4)
norm_effect_auc_df <- sig_noise_df %>%
    mutate(t_eval = 2^-t_fctr) %>%
    group_by(pipe, method, dist_method, seq_lab, seq_run, biosample_id) %>%
    summarise(auc = -pracma::trapz(x = t_eval, y = median_sig_noise))

unweighted_levels <- c("RAW", "rare2000", "rare5000", "rare10000", "rareq15")
weighted_levels <- c(unweighted_levels, "CSS","TSS","UQ","RLE","TMM")

norm_effect_auc_fit <- norm_effect_auc_df %>%
    ungroup() %>%
    mutate(seq_run = as.numeric(seq_run),
           seq_run_num = if_else(seq_lab == "jhu", seq_run, 2 + seq_run),
           seq_run_num = factor(seq_run_num)) %>%
    mutate(method = factor(method, levels = weighted_levels)) %>%
    filter(seq_run == 1, seq_lab == "nist") %>% 
    group_by(dist_method, pipe) %>%
    nest() %>%
    mutate(fit = map(data, ~lmer(log10(auc) ~ method + (1 | biosample_id), data = .)))
```

```{r}
fit <- norm_effect_auc_fit$fit[[1]]
dat <- norm_effect_auc_fit$data[[1]]
```



```{r}
summary(fit)
```

```{r}
plot(fit)
```

```{r}
aug_df <- broom::augment(fit, dat)
```


```{r}
ggplot(aug_df) + geom_point(aes(x = log10(auc), y = .resid)) + theme_bw() + 
    labs(x = "Signal to Noise", y = "Residual")
```


```{r}
ggplot(aug_df) + 
    geom_qq(aes(sample = scale(.resid))) +
    geom_abline(aes(intercept = 0, slope = 1)) + 
    theme_bw() + 
    ggtitle("QQ-Plot")
```

```{r}
ggplot(aug_df) + 
    geom_point(aes(x = .fitted, y = .resid)) + 
    theme_bw() + 
    labs(x = "Fitted Values", y = "Residuals")
```

```{r}
summary(fit)
```

```{r}
broom::tidy(fit) %>% 
    rename(normalization = term) %>% 
    mutate(normalization = if_else(normalization == "(Intercept)",
                                   "RAW", 
                                   str_remove(normalization, "method"))) %>%
    filter(group == "fixed")
    
```

```{r}
tidy_fit_df <- broom::tidy(fit) %>% 
    dplyr::rename(normalization = term) %>% 
    mutate(normalization = if_else(normalization == "(Intercept)",
                                   "RAW", 
                                   str_remove(normalization, "method"))) %>%
    filter(group == "fixed")

confint_dat <- confint(fit)

fit_est_df <- as.data.frame(confint_dat) %>% 
    rownames_to_column(var = "normalization") %>% 
    filter(!grepl("sig", normalization)) %>% 
    gather("conf_int","est", -normalization) %>% 
    spread(normalization, est) %>%
    rename(RAW = `(Intercept)`) %>%
    gather("normalization","est", -conf_int, -RAW) %>% 
    mutate(est = RAW + est) %>% 
    mutate(normalization = str_remove(normalization, "method")) %>%
    spread(normalization, est) %>% 
    gather("normalization","est", -conf_int) %>% 
    mutate(conf_int = if_else(conf_int == "2.5 %", "lci","uci")) %>% 
    spread(conf_int, est) 

rownames(confint_dat)[-c(1:2)]
rownames(confint_dat) 
fit_est_df
mod_betas <- fit@beta
normalization <- rownames(confint_dat)[-c(1:2)]
est <- c(mod_betas[1], mod_betas[1] + mod_betas[-1])
sig_noise_est <- data_frame(normalization, est)  %>%
    mutate(normalization = if_else(normalization == "(Intercept)",
                                   "RAW", 
                                   str_remove(normalization, "method"))) %>%
    left_join(fit_est_df) %>% 
    mutate(est = 10^est, lci = 10^lci, uci = 10^uci) %>% 
    left_join(tidy_fit_df)
```

```{r fig.cap = "Weighted average signal to noise ratio estimate and 95 CI for raw and normalized count data. Estimates calculated using a mixed effects linear model using subject as random effect. The horizontal solid line is the unnormalized count signal to noise estimate and horizontal dashed lines indicate 95 CI. The points and line ranges indicate the model estimate and 95 CI for the different normalization methods. T-statistic indicate difference of normalized counts from raw counts for each method."}
raw_sig_noise <- sig_noise_est %>% filter(normalization == "RAW")
sig_noise_est %>% filter(normalization != "RAW") %>% 
    ggplot() + 
    geom_point(aes(x = normalization, y = est)) + 
    geom_linerange(aes(x = normalization, ymin = lci, ymax = uci)) + 
    geom_hline(data = raw_sig_noise, aes(yintercept = est)) + 
    geom_hline(data = raw_sig_noise, aes(yintercept = uci), linetype = 2) + 
    geom_hline(data = raw_sig_noise, aes(yintercept = lci), linetype = 2) + 
    geom_text(aes(x = normalization, y = 0.75*min(lci), label = round(statistic,2))) + 
    theme_bw() +
    labs(x = "Normalization Method", y = "Signal/Noise Estimate")
```

```{r}
ne_fig <- function(sig_noise_est){
    raw_sig_noise <- sig_noise_est %>% filter(normalization == "RAW")
    
    sig_noise_est %>% filter(normalization != "RAW") %>% ggplot() +
        geom_point(aes(x = normalization, y = est)) +
        geom_linerange(aes(x = normalization, ymin = lci, ymax = uci)) +
        geom_hline(data = raw_sig_noise, aes(yintercept = est)) +
        geom_hline(data = raw_sig_noise, aes(yintercept = uci), linetype = 2) +
        geom_hline(data = raw_sig_noise, aes(yintercept = lci), linetype = 2) +
        geom_text(aes(x = normalization, y = 0.75 * min(lci), 
                      label = round(statistic, 2))) +
        theme_bw() +
        labs(x = "Normalization Method", y = "Signal/Noise Estimate")
}


tidy_ne <- function(fit){
    tidy_fit_df <- broom::tidy(fit) %>% 
    rename(normalization = term) %>% 
    mutate(normalization = if_else(normalization == "(Intercept)",
                                   "RAW", 
                                   str_remove(normalization, "method"))) %>%
    filter(group == "fixed")

    confint_dat <- confint(fit)
    
    fit_est_df <- as.data.frame(confint_dat) %>% 
        rownames_to_column(var = "normalization") %>% 
        filter(!grepl("sig", normalization)) %>% 
        gather("conf_int","est", -normalization) %>% 
        spread(normalization, est) %>%
        rename(RAW = `(Intercept)`) %>%
        gather("normalization","est", -conf_int, -RAW) %>% 
        mutate(est = RAW + est) %>% 
        mutate(normalization = str_remove(normalization, "method")) %>%
        spread(normalization, est) %>% 
        gather("normalization","est", -conf_int) %>% 
        mutate(conf_int = if_else(conf_int == "2.5 %", "lci","uci")) %>% 
        spread(conf_int, est) 
    
    rownames(confint_dat)[-c(1:2)]
    rownames(confint_dat) 
    fit_est_df
    mod_betas <- fit@beta
    mod_betas
    normalization
    normalization <- rownames(confint_dat)[-c(1:2)]
    est <- c(mod_betas[1], mod_betas[1] + mod_betas[-1])
    data_frame(normalization, est)  %>%
        mutate(normalization = if_else(normalization == "(Intercept)",
                                       "RAW", 
                                       str_remove(normalization, "method"))) %>%
        left_join(fit_est_df) %>% 
        mutate(est = 10^est, lci = 10^lci, uci = 10^uci) %>% 
        left_join(tidy_fit_df)
}

norm_effect_plot <- function(fit, pipe, metric){
    fig_title <- paste0(pipe, "-", metric)
    sig_noise_est <- tidy_ne(fit) 
    ne_fig(sig_noise_est) + ggtitle(fig_title)
}
```

```{r}
norm_effect_auc_fit %>% 
    {pmap(list(.$fit, .$pipe, .$dist_method), norm_effect_plot)}
```

## LMER Diagnostics 
Extracting fit results for pipelines and metrics
```{r}
lmer_diag_plots <- function(fit, dat, pipe, metric) {
    fig_title <- paste0(pipe, "-", metric)
    aug_df <- broom::augment(fit, dat)
    
    value_resid <- ggplot(aug_df) + 
        geom_point(aes(x = log10(auc), y = .resid)) + 
        theme_bw() + 
        labs(x = "Signal to Noise", y = "Residual")

    fitted_v_resid <- ggplot(aug_df) + 
        geom_point(aes(x = .fitted, y = .resid)) + 
        theme_bw() + 
        labs(x = "Fitted Values", y = "Residuals")
    
    qq_plot <- ggplot(aug_df) +
        geom_qq(aes(sample = scale(.resid))) +
        geom_abline(aes(intercept = 0, slope = 1)) +
        theme_bw() + 
        labs(x = "Theoretical Quantiles", y = "Center-Scaled Residuals")
    
    ggarrange(value_resid, fitted_v_resid, qq_plot, nrow = 1, ncol = 3) %>% 
        annotate_figure(top = text_grob(fig_title, hjust = 2))
}
```

```{r}
lmer_diag_plots(fit,dat, "DADA2", "Bray")
```

```{r}
norm_effect_auc_fit %>% 
    mutate(diag_plots = pmap(list(fit, data, pipe, dist_method), lmer_diag_plots)) %>% 
    {print(.$diag_plots)}
```



```{r}
norm_effect_auc_fit %>% 
    select(pipe, dist_method, fit) %>% 
    mutate(dist_method = str_remove(dist_method, "_dist")) %>% 
    mutate(fit_glance = map(fit, broom::glance)) %>% 
    unnest(fit_glance) %>% 
    select(-fit) %>% 
    knitr::kable(digits = 3, format = "html") %>% 
    kableExtra::kable_styling() %>% 
    kableExtra::collapse_rows()
```

__NOTES__  
_Methods_  


_Results_  


_Interpretation_   


_Potential analysis improvements_   

